Kalvin branch
BCIT-SSD-2020-21/front-end-project-nappingbed pull request #38
Opened 2020-10-21 23:15 UTC by KalTang

2020-10-26 17:53 UTC, Wayl123 requested changes
I notice an empty file login.js, do remove that, only add it when you are using it.
As mentioned, add new breakpoint for your login page so the right side of the page doesn't cut off in the middle.

2020-10-26 17:53 UTC, Wayl123 commented on login.html
>  </html>
We decide on using space 4 so make it into space 4 instead of space 2.

2020-10-26 17:53 UTC, Wayl123 commented on scss/Register/index.scss
> +@import "register";
Not sure if this is needed but guess it doesn't hurt.

2020-10-26 17:53 UTC, Wayl123 commented
Also change space 2 to space 4.

2020-10-27 03:36 UTC, Wayl123 approved these changes

2020-10-27 03:56 UTC, stevenlai4 approved these changes
Good to merge back to main

2020-10-27 03:57 UTC, merged