Gallery images
BCIT-SSD-2020-21/front-end-project-nappingbed pull request #66
Opened 2020-10-26 23:20 UTC by karenm08

#57 #26 
fixed contact page validation

2020-10-26 23:27 UTC, Wayl123 approved these changes
Added contact.js back weeeeee.

2020-10-26 23:51 UTC, stevenlai4 requested changes
I put comments below

2020-10-26 23:51 UTC, stevenlai4 commented on scss/gallery/_content.scss
> +    font-family: 'Cormorant', serif;
I put this line in the body scss as the global font already

2020-10-26 23:51 UTC, stevenlai4 commented on scss/contact/contact.scss
> +    font-family: 'Cormorant', serif;
This is in global body scss as well

2020-10-26 23:56 UTC, Wayl123 requested changes
Yeah I also notice the error steven is talking about.

2020-10-27 00:14 UTC, Wayl123 approved these changes
The error I notice have been fixed -w-b.

2020-10-27 00:27 UTC, merged